[
    {
        "RN": "1",
        "QUERY_ID": "252847768",
        "QTYPE": "B",
        "SENDERNAME": "KIRAN SARDE",
        "SENDEREMAIL": "kiransarde123@gmail.com",
        "SUBJECT": "Requirement for MLM Software Development Services",
        "DATE_RE": "16 Sep 2020",
        "DATE_R": "16-Sep-20",
        "DATE_TIME_RE": "16-Sep-2020 11:51:59 AM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9834850110",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200916115159",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am interested in buying MLM Software Development. \n\nKindly send me price and other details.<br>Probable Unit Price : 20,000 to 50,000",
        "ENQ_ADDRESS": "Pune, Maharashtra",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Pune",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": "MLM Software Development Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "2",
        "QUERY_ID": "252819892",
        "QTYPE": "B",
        "SENDERNAME": "Mukesh",
        "SENDEREMAIL": null,
        "SUBJECT": "Requirement for E-Learning Application Development",
        "DATE_RE": "16 Sep 2020",
        "DATE_R": "16-Sep-20",
        "DATE_TIME_RE": "16-Sep-2020 10:37:02 AM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8519053637",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200916103702",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for service provider for E-Learning Application Development.\r\n\r\nKindly send me price and other details.<br>Probable Unit Price : 20,000 to 50,000",
        "ENQ_ADDRESS": "Gwalior, Madhya Pradesh",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Gwalior",
        "ENQ_STATE": "Madhya Pradesh",
        "PRODUCT_NAME": "E-Learning Application Development",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "3",
        "QUERY_ID": "252819565",
        "QTYPE": "B",
        "SENDERNAME": "Shrikant Bhangdiya",
        "SENDEREMAIL": "s.bhangdiya@gmail.com",
        "SUBJECT": "Requirement for Document Management Software",
        "DATE_RE": "16 Sep 2020",
        "DATE_R": "16-Sep-20",
        "DATE_TIME_RE": "16-Sep-2020 10:36:05 AM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9545599953",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200916103605",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am interested in buying Document Management Software. \n\nKindly send me price and other details.<br>Quantity : 1 Piece<br>Timeline : Instant Requirement<br>Need Demo : Yes<br>Why do you need this : For Personal\/Business Use<br>Probable Order Value : 20,000 to 50,000",
        "ENQ_ADDRESS": "Mumbai, Maharashtra",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Mumbai",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": "Document Management Software",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "4",
        "QUERY_ID": "252808175",
        "QTYPE": "B",
        "SENDERNAME": "Karan",
        "SENDEREMAIL": "abc659659@gmail.com",
        "SUBJECT": "Requirement for SATTA Matka Game App Development",
        "DATE_RE": "16 Sep 2020",
        "DATE_R": "16-Sep-20",
        "DATE_TIME_RE": "16-Sep-2020 10:00:59 AM",
        "GLUSR_USR_COMPANYNAME": "Ico Support",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9777880766",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200916100059",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for SATTA Matka Game App Development.\nCall me\nKindly send me price and other details.<br>Start Date \/ Month : Today<br>Service Location : India<br>Probable Unit Price : Rs. 40,000 - 75,000<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Plot No-13,Bhubaneshwar, Bhubaneswar, Odisha,         751001",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Bhubaneswar",
        "ENQ_STATE": "Odisha",
        "PRODUCT_NAME": "SATTA Matka Game App Development",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "5",
        "QUERY_ID": "252807709",
        "QTYPE": "B",
        "SENDERNAME": "Balandar Shakhar Vishwakarma",
        "SENDEREMAIL": "goluvish43@gmail.com",
        "SUBJECT": "Requirement for Mobile Application Development",
        "DATE_RE": "16 Sep 2020",
        "DATE_R": "16-Sep-20",
        "DATE_TIME_RE": "16-Sep-2020 09:59:24 AM",
        "GLUSR_USR_COMPANYNAME": "farmeng",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-7987304493",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200916095924",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for Mobile Application Development.\n\nKindly send me price and other details.<br>Probable Unit Price : 20,000 to 50,000<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Indore, Madhya Pradesh",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Indore",
        "ENQ_STATE": "Madhya Pradesh",
        "PRODUCT_NAME": "Mobile Application Development",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "6",
        "QUERY_ID": "252807073",
        "QTYPE": "B",
        "SENDERNAME": "Vijay Jain",
        "SENDEREMAIL": "vijayjain14141@gmail.com",
        "SUBJECT": "Requirement for Mobile Application Development",
        "DATE_RE": "16 Sep 2020",
        "DATE_R": "16-Sep-20",
        "DATE_TIME_RE": "16-Sep-2020 09:57:15 AM",
        "GLUSR_USR_COMPANYNAME": "Advik Pristine",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-6232873041",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200916095715",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for Mobile Application Development.\n\nKindly send me price and other details.<br>Probable Unit Price : 20,000 to 50,000<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Vaishali Nagar, Sehore, Madhya Pradesh,         466001",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Sehore",
        "ENQ_STATE": "Madhya Pradesh",
        "PRODUCT_NAME": "Mobile Application Development",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": "advikpristine@gmail.com",
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "7",
        "QUERY_ID": "1500059557",
        "QTYPE": "W",
        "SENDERNAME": "Adnan",
        "SENDEREMAIL": "rahman.adnan200@gmail.com",
        "SUBJECT": "Requirement for Pathology Lab Software",
        "DATE_RE": "16 Sep 2020",
        "DATE_R": "16-Sep-20",
        "DATE_TIME_RE": "16-Sep-2020 08:00:18 AM",
        "GLUSR_USR_COMPANYNAME": "RKY Enterprises",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8090457764",
        "COUNTRY_FLAG": "",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200916080018",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I want to buy Pathology Lab Software.\r\n\r\nKindly send me price and other details.\n\n Quantity:   1   Sofware\n Timeline:   Instant Requirement \n Need Demo:   Yes \n Target Price:   Up To 10000 INR \n\n\nAdditional Updates on Buyer's Requirement :\n",
        "ENQ_ADDRESS": "Mau, Uttar Pradesh, 275101",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Mau",
        "ENQ_STATE": "Uttar Pradesh",
        "PRODUCT_NAME": "Pathology Lab Software",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "8",
        "QUERY_ID": "252645187",
        "QTYPE": "B",
        "SENDERNAME": "Anant Jain",
        "SENDEREMAIL": "mr.anantjain43@gmail.com",
        "SUBJECT": "Requirement for IOS Application Development",
        "DATE_RE": "15 Sep 2020",
        "DATE_R": "15-Sep-20",
        "DATE_TIME_RE": "15-Sep-2020 08:04:31 PM",
        "GLUSR_USR_COMPANYNAME": "Benchmark Production",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9860231004",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200915200431",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for service provider for IOS Application Development and \t\t\t\t\t\t\t\tAndroid Application Development Services.\r\n\r\nKindly send me price and other details.<br>Project Duration : 1 Months To 1.5 Months<br>Usage\/Application : For Business Use<br>Probable Unit Price : 20,000 to 50,000",
        "ENQ_ADDRESS": "Plot No. 1044, Swastik Mobile, Nagpur, Maharashtra,         440024",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Nagpur",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": "IOS Application Development",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "9",
        "QUERY_ID": "1499661685",
        "QTYPE": "W",
        "SENDERNAME": "Brijesh Rai",
        "SENDEREMAIL": "brijeshdeep3107@gmail.com",
        "SUBJECT": "Requirement for Website Development Services",
        "DATE_RE": "15 Sep 2020",
        "DATE_R": "15-Sep-20",
        "DATE_TIME_RE": "15-Sep-2020 06:26:42 PM",
        "GLUSR_USR_COMPANYNAME": "Rai And Sones",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8400982260",
        "COUNTRY_FLAG": "",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200915182642",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for Website Development Services.\n\nKindly send me price and other details.\n\n Probable Requirement Type:   Business Use \n Other Products Viewed by Buyer:   15 Days Shopify Store Development Service, Language Required: English \n",
        "ENQ_ADDRESS": "Datia, Madhya Pradesh",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Datia",
        "ENQ_STATE": "Madhya Pradesh",
        "PRODUCT_NAME": "Website Development Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "10",
        "QUERY_ID": "252613673",
        "QTYPE": "B",
        "SENDERNAME": "Md Roshan",
        "SENDEREMAIL": "roshanroshan5877@gmail.com",
        "SUBJECT": "Requirement for Online Ecommerce Web and Mobile Application",
        "DATE_RE": "15 Sep 2020",
        "DATE_R": "15-Sep-20",
        "DATE_TIME_RE": "15-Sep-2020 05:24:08 PM",
        "GLUSR_USR_COMPANYNAME": "Kurti",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9304153481",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200915172408",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for service provider for Online Ecommerce Web and Mobile Application.\r\n\r\nKindly send me price and other details.<br>Service Location : Ranchi<br>Probable Unit Price : Rs. 12,000 - 35,000",
        "ENQ_ADDRESS": "Sony, Ranchi, Jharkhand,         834001",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Ranchi",
        "ENQ_STATE": "Jharkhand",
        "PRODUCT_NAME": "Online Ecommerce Web and Mobile Application",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "11",
        "QUERY_ID": "252613087",
        "QTYPE": "B",
        "SENDERNAME": "ABHIMANYU CHAUDHARY",
        "SENDEREMAIL": "meabhi868@gmail.com",
        "SUBJECT": "Requirement for Ecommerce Solutions",
        "DATE_RE": "15 Sep 2020",
        "DATE_R": "15-Sep-20",
        "DATE_TIME_RE": "15-Sep-2020 05:22:05 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8929144639",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200915172205",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for Ecommerce Solutions.\n\nKindly send me price and other details.",
        "ENQ_ADDRESS": "Bengaluru, Karnataka",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Bengaluru",
        "ENQ_STATE": "Karnataka",
        "PRODUCT_NAME": "Ecommerce Solutions",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "12",
        "QUERY_ID": "241598691",
        "QTYPE": "P",
        "SENDERNAME": "Sumit Jain",
        "SENDEREMAIL": "vidhyait0282@gmail.com",
        "SUBJECT": "Buyer Call",
        "DATE_RE": "15 Sep 2020",
        "DATE_R": "15-Sep-20",
        "DATE_TIME_RE": "15-Sep-2020 04:28:45 PM",
        "GLUSR_USR_COMPANYNAME": "Vidhya Innovative Technology",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "7415737770",
        "COUNTRY_FLAG": "",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200915000000",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": null,
        "ENQ_ADDRESS": "",
        "ENQ_CALL_DURATION": "255 Secs",
        "ENQ_RECEIVER_MOB": "8009765441",
        "ENQ_CITY": "Indore",
        "ENQ_STATE": "Madhya Pradesh",
        "PRODUCT_NAME": null,
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "13",
        "QUERY_ID": "252589605",
        "QTYPE": "B",
        "SENDERNAME": "Kumar Bhadur",
        "SENDEREMAIL": null,
        "SUBJECT": "Requirement for Hospital Software",
        "DATE_RE": "15 Sep 2020",
        "DATE_R": "15-Sep-20",
        "DATE_TIME_RE": "15-Sep-2020 04:02:20 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9140847769",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200915160220",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I want to buy Hospital Software.\r\n\r\nKindly send me price and other details.<br>Quantity : 1 Piece<br>Need Demo : Yes<br>Timeline : Instant Requirement<br>Probable Requirement Type : Business Use<br>Probable Order Value : Rs. 15,000 - 40,000",
        "ENQ_ADDRESS": "Faizabad, Uttar Pradesh",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Faizabad",
        "ENQ_STATE": "Uttar Pradesh",
        "PRODUCT_NAME": "Hospital Software",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "14",
        "QUERY_ID": "252584401",
        "QTYPE": "B",
        "SENDERNAME": "Ashwin Jain",
        "SENDEREMAIL": "elanzafashion@gmail.com",
        "SUBJECT": "Requirement for E Commerce Website Design Service",
        "DATE_RE": "15 Sep 2020",
        "DATE_R": "15-Sep-20",
        "DATE_TIME_RE": "15-Sep-2020 03:44:35 PM",
        "GLUSR_USR_COMPANYNAME": "Ambika Enterprises",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9870590985",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200915154435",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am interested in E Commerce Website Design Service<br>Website Already Exists : No<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Mumbai, Maharashtra",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Mumbai",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": "E Commerce Website Design Service",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "15",
        "QUERY_ID": "252573183",
        "QTYPE": "B",
        "SENDERNAME": "Anirudh Ojha",
        "SENDEREMAIL": "jyotiheat52@gmail.com",
        "SUBJECT": "Requirement for Blogging Dynamic Website Development Service",
        "DATE_RE": "15 Sep 2020",
        "DATE_R": "15-Sep-20",
        "DATE_TIME_RE": "15-Sep-2020 03:06:44 PM",
        "GLUSR_USR_COMPANYNAME": "Jyoti Heat Treatment Service",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9967111268",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200915150644",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am interested in Blogging Dynamic Website Development Service<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "room no 301\/8 siddharth nager ,naamdev chawal, Jabalpur, Madhya Pradesh,         400080",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Jabalpur",
        "ENQ_STATE": "Madhya Pradesh",
        "PRODUCT_NAME": "Blogging Dynamic Website Development Service",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "16",
        "QUERY_ID": "252547619",
        "QTYPE": "B",
        "SENDERNAME": "Swapan Saha",
        "SENDEREMAIL": "s_sahark@rediffmail.com",
        "SUBJECT": "Requirement for Spice Packaging Graphics Designing",
        "DATE_RE": "15 Sep 2020",
        "DATE_R": "15-Sep-20",
        "DATE_TIME_RE": "15-Sep-2020 01:37:26 PM",
        "GLUSR_USR_COMPANYNAME": "Saha Technocrats",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9836620123",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200915133726",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for service provider for Spice Packaging Graphics Designing.\r\n\r\nI will need the samples first.\r\n\r\nKindly share the product details via WhatsApp\/SMS\/Email.\r\n\r\nKindly send me price and other details.<br>Service Location : Kolkata<br>Usage\/Application : For Business Use",
        "ENQ_ADDRESS": "82 P.C.ghosh Road Vip Laketown, Kolkata, West Bengal,         700048",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Kolkata",
        "ENQ_STATE": "West Bengal",
        "PRODUCT_NAME": "Spice Packaging Graphics Designing",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "17",
        "QUERY_ID": "252540602",
        "QTYPE": "B",
        "SENDERNAME": "Tanmoy",
        "SENDEREMAIL": "tanmoybanerjee89@gmail.com",
        "SUBJECT": "Requirement for Matka Software Development",
        "DATE_RE": "15 Sep 2020",
        "DATE_R": "15-Sep-20",
        "DATE_TIME_RE": "15-Sep-2020 01:12:22 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8509782090",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200915131222",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am interested in Offline & Online Advance Satta Matka Software Development, Development Platforms: Browser Base And<br>Probable Unit Price : 20,000 to 50,000<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Bardhaman, West Bengal",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Bardhaman",
        "ENQ_STATE": "West Bengal",
        "PRODUCT_NAME": "Matka Software Development",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "18",
        "QUERY_ID": "252540104",
        "QTYPE": "B",
        "SENDERNAME": "Dilip Kumar",
        "SENDEREMAIL": "chauhanmanoj47556@gmail.com",
        "SUBJECT": "Requirement for Online E Commerce and Mobile Application Business Service",
        "DATE_RE": "15 Sep 2020",
        "DATE_R": "15-Sep-20",
        "DATE_TIME_RE": "15-Sep-2020 01:10:45 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-6396656487",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200915131045",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "Yes Product Name: Online E Commerce And Mobile Application Business Service<br>Website Already Exists : Yes<br>Template Type : Other<br>Job Completion Timeframe : Student",
        "ENQ_ADDRESS": "Agra, Uttar Pradesh",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Agra",
        "ENQ_STATE": "Uttar Pradesh",
        "PRODUCT_NAME": "Online E Commerce and Mobile Application Business Service",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "19",
        "QUERY_ID": "1498931623",
        "QTYPE": "W",
        "SENDERNAME": "Raj",
        "SENDEREMAIL": null,
        "SUBJECT": "Requirement for Branding Logo Design",
        "DATE_RE": "15 Sep 2020",
        "DATE_R": "15-Sep-20",
        "DATE_TIME_RE": "15-Sep-2020 11:40:10 AM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-6306151347",
        "COUNTRY_FLAG": "",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200915114010",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "Please send pricing and details of 'Branding Logo Design'\n\n Probable Requirement Type:   Business Use \n Other Products Viewed by Buyer:   Logo Design \n",
        "ENQ_ADDRESS": "Jhansi, Uttar Pradesh",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Jhansi",
        "ENQ_STATE": "Uttar Pradesh",
        "PRODUCT_NAME": "Branding Logo Design",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "20",
        "QUERY_ID": "252506615",
        "QTYPE": "B",
        "SENDERNAME": "Rohit",
        "SENDEREMAIL": "royalmatka07@gmail.com",
        "SUBJECT": "Requirement for Android Application Development Services",
        "DATE_RE": "15 Sep 2020",
        "DATE_R": "15-Sep-20",
        "DATE_TIME_RE": "15-Sep-2020 11:34:10 AM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-7387725274",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200915113410",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for Android Application Development Services.\n\nKindly send me price and other details.<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Nagpur, Maharashtra",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Nagpur",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": "Android Application Development Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "21",
        "QUERY_ID": "252491665",
        "QTYPE": "B",
        "SENDERNAME": "Shubham",
        "SENDEREMAIL": "mrdreamer8888@gmail.com",
        "SUBJECT": "Requirement for Online Exam Software Development",
        "DATE_RE": "15 Sep 2020",
        "DATE_R": "15-Sep-20",
        "DATE_TIME_RE": "15-Sep-2020 10:54:59 AM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8888242906",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200915105459",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for Online Exam Software Development.\n\nKindly send me price and other details.<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Nagpur, Maharashtra",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Nagpur",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": "Online Exam Software Development",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "22",
        "QUERY_ID": "252291847",
        "QTYPE": "B",
        "SENDERNAME": "Aeshu Patidar",
        "SENDEREMAIL": "aeshupatidar1@gmail.com",
        "SUBJECT": "Requirement for Education Website Development Services",
        "DATE_RE": "14 Sep 2020",
        "DATE_R": "14-Sep-20",
        "DATE_TIME_RE": "14-Sep-2020 06:24:29 PM",
        "GLUSR_USR_COMPANYNAME": "Indian Grafic Designer",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8209762881",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200914182429",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for service provider for Education Website Development Services.\r\n\r\n\r\nRest details i will discuss with service providers.<br>I am interested in : Education Website Development Services<br>Service Location : Jaipur<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Jaipur, Rajasthan",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Jaipur",
        "ENQ_STATE": "Rajasthan",
        "PRODUCT_NAME": "Education Website Development Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": "indiangraphicdesigners@gmail.com",
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "23",
        "QUERY_ID": "252285511",
        "QTYPE": "B",
        "SENDERNAME": "Mr.Apurba Das",
        "SENDEREMAIL": "apurbadas528246@gmail.com",
        "SUBJECT": "Requirement for E Commerce Website Design",
        "DATE_RE": "14 Sep 2020",
        "DATE_R": "14-Sep-20",
        "DATE_TIME_RE": "14-Sep-2020 05:55:38 PM",
        "GLUSR_USR_COMPANYNAME": "APURBA SMART PRINTING",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9748244513",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200914175538",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "E Commerce Website Design, Chat, Online as well as 24 7.<br>Website Already Exists : No<br>Template Type : Customized<br>Job Completion Timeframe : customised gift shop<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "S. A Faroque Road, Kolkata, West Bengal,         700018",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Kolkata",
        "ENQ_STATE": "West Bengal",
        "PRODUCT_NAME": "E Commerce Website Design",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": "+91-8777218344",
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "24",
        "QUERY_ID": "252260178",
        "QTYPE": "B",
        "SENDERNAME": "Manish Kumar",
        "SENDEREMAIL": "manishworld198@gmail.com",
        "SUBJECT": "Requirement for Web Development and Marketing Services",
        "DATE_RE": "14 Sep 2020",
        "DATE_R": "14-Sep-20",
        "DATE_TIME_RE": "14-Sep-2020 04:20:19 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9651426517",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200914162019",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for service provider for Web Development and Marketing Services.<br>I am interested in : Web Service<br>Service Location : Gorakhpur<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Gorakhpur, Uttar Pradesh",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Gorakhpur",
        "ENQ_STATE": "Uttar Pradesh",
        "PRODUCT_NAME": "Web Development and Marketing Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "25",
        "QUERY_ID": "241270870",
        "QTYPE": "P",
        "SENDERNAME": "Anand Ashok Suryavanshi",
        "SENDEREMAIL": "anandsuryavanshi60@gmail.com",
        "SUBJECT": "Buyer Call",
        "DATE_RE": "14 Sep 2020",
        "DATE_R": "14-Sep-20",
        "DATE_TIME_RE": "14-Sep-2020 02:46:42 PM",
        "GLUSR_USR_COMPANYNAME": "Suryavanshi Fabrication",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "9833782713",
        "COUNTRY_FLAG": "",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200914000000",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": null,
        "ENQ_ADDRESS": "",
        "ENQ_CALL_DURATION": "25 Secs",
        "ENQ_RECEIVER_MOB": "8009765441",
        "ENQ_CITY": "Mumbai",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": null,
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "26",
        "QUERY_ID": "241270623",
        "QTYPE": "P",
        "SENDERNAME": "Anand Ashok Suryavanshi",
        "SENDEREMAIL": "anandsuryavanshi60@gmail.com",
        "SUBJECT": "Buyer Call",
        "DATE_RE": "14 Sep 2020",
        "DATE_R": "14-Sep-20",
        "DATE_TIME_RE": "14-Sep-2020 02:45:59 PM",
        "GLUSR_USR_COMPANYNAME": "Suryavanshi Fabrication",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "9833782713",
        "COUNTRY_FLAG": "",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200914000000",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": null,
        "ENQ_ADDRESS": "",
        "ENQ_CALL_DURATION": "37 Secs",
        "ENQ_RECEIVER_MOB": "8009765441",
        "ENQ_CITY": "Mumbai",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": null,
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "27",
        "QUERY_ID": "252228836",
        "QTYPE": "B",
        "SENDERNAME": "Anjani Rajput",
        "SENDEREMAIL": "anjanirajput983@gmail.com",
        "SUBJECT": "Requirement for Mobile Application Development Service",
        "DATE_RE": "14 Sep 2020",
        "DATE_R": "14-Sep-20",
        "DATE_TIME_RE": "14-Sep-2020 02:40:12 PM",
        "GLUSR_USR_COMPANYNAME": "Anjani Manufacturing Solar Solutions",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-7678650822",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200914144012",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for service provider for Mobile Application Development Service.<br>I am interested in : Mobile Application Development Service<br>Service Location : Etah<br>Probable Unit Price : 20,000 to 50,000<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Ma Purna Giri Colony, Railway Chouch Ke Peech Kasganje, Etah, Uttar Pradesh,         207241",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Etah",
        "ENQ_STATE": "Uttar Pradesh",
        "PRODUCT_NAME": "Mobile Application Development Service",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "28",
        "QUERY_ID": "252224543",
        "QTYPE": "B",
        "SENDERNAME": "Nitin",
        "SENDEREMAIL": "nitinverna47@gmail.com",
        "SUBJECT": "Requirement for Website and Mobile App Development",
        "DATE_RE": "14 Sep 2020",
        "DATE_R": "14-Sep-20",
        "DATE_TIME_RE": "14-Sep-2020 02:25:46 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-7508655123",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200914142546",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for service provider for Website and Mobile App Development for my Garments Business to make it online as well.\nKindly send me price and other details.<br>I am interested in : IOS Application Development, Android Application Development Services<br>Project Duration : Long Term<br>Start Date \/ Month : Immediately<br>Probable Unit Price : 20,000 to 50,000<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Mohali, Punjab",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Mohali",
        "ENQ_STATE": "Punjab",
        "PRODUCT_NAME": "Website and Mobile App Development",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "29",
        "QUERY_ID": "252213544",
        "QTYPE": "B",
        "SENDERNAME": "Inayatullaa",
        "SENDEREMAIL": "mohammadinayatullaa@gmail.com",
        "SUBJECT": "Requirement for Lead Crm Website Development Service",
        "DATE_RE": "14 Sep 2020",
        "DATE_R": "14-Sep-20",
        "DATE_TIME_RE": "14-Sep-2020 01:46:17 PM",
        "GLUSR_USR_COMPANYNAME": "Ideal India",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9296108999",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200914134617",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for service provider for Lead Crm Website Development Service.<br>Service Location : Machilipatnam<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Main Road, Machilipatnam, Andhra Pradesh,         521001",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Machilipatnam",
        "ENQ_STATE": "Andhra Pradesh",
        "PRODUCT_NAME": "Lead Crm Website Development Service",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": "idealindiaeservices@gmail.com",
        "MOBILE_ALT": "+91-8074391844",
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "30",
        "QUERY_ID": "252204212",
        "QTYPE": "B",
        "SENDERNAME": "Syed Khurshid Alam",
        "SENDEREMAIL": null,
        "SUBJECT": "Requirement for Grocery Shopping Software Development Service",
        "DATE_RE": "14 Sep 2020",
        "DATE_R": "14-Sep-20",
        "DATE_TIME_RE": "14-Sep-2020 01:13:15 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9610158847",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200914131315",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am interested in Grocery shopping software development service Product Name: Grocery shopping software development service<br>I am interested in : Shop<br>Service Location : Digge chok<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Ajmer, Rajasthan",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Ajmer",
        "ENQ_STATE": "Rajasthan",
        "PRODUCT_NAME": "Grocery Shopping Software Development Service",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "31",
        "QUERY_ID": "252193962",
        "QTYPE": "B",
        "SENDERNAME": "Devidas Raut",
        "SENDEREMAIL": "devidasraut@rediffmail.com",
        "SUBJECT": "Requirement for Android Application Development Services",
        "DATE_RE": "14 Sep 2020",
        "DATE_R": "14-Sep-20",
        "DATE_TIME_RE": "14-Sep-2020 12:43:07 PM",
        "GLUSR_USR_COMPANYNAME": "Kalyani Softwares",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8007424999",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200914124307",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I want to buy Android Application Development Services.\n\nKindly send me price and other details.<br>Project Duration : 45 Days<br>Start Date \/ Month : October 2020<br>Probable Unit Price : 20,000 to 50,000<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Jejuri Taluka Purandar, Pune, Maharashtra,         412303",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Pune",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": "Android Application Development Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": "kalyanianalytics@gmail.com",
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "32",
        "QUERY_ID": "252187280",
        "QTYPE": "B",
        "SENDERNAME": "Hirok Saha",
        "SENDEREMAIL": "slgfinsol@yahoo.com",
        "SUBJECT": "Requirement for School Management System",
        "DATE_RE": "14 Sep 2020",
        "DATE_R": "14-Sep-20",
        "DATE_TIME_RE": "14-Sep-2020 12:25:01 PM",
        "GLUSR_USR_COMPANYNAME": "Siliguri Financial Solutions",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9832028495",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200914122501",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I want to buy School Management System, For Php, Mysql.\n\nKindly send me price and other details.<br>Modules\/Features : Transport, Attendance, Fees Collection<br>Need Demo : Yes<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Sanat Trade Center 1st Floor,Sevok Road Siliguri,Darjeeling,West Bengal, Siliguri, West Bengal,         734001",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Siliguri",
        "ENQ_STATE": "West Bengal",
        "PRODUCT_NAME": "School Management System",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": "hirok_saha@yahoo.co.in",
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "33",
        "QUERY_ID": "252157338",
        "QTYPE": "B",
        "SENDERNAME": "Dhurv Saxena",
        "SENDEREMAIL": "dhurvsaxena2@gmail.com",
        "SUBJECT": "Requirement for Website Designing",
        "DATE_RE": "14 Sep 2020",
        "DATE_R": "14-Sep-20",
        "DATE_TIME_RE": "14-Sep-2020 11:08:29 AM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8393950970",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200914110829",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking  Website Designing.<br>I am interested in : School Web Design",
        "ENQ_ADDRESS": "Kichha, Uttarakhand",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Kichha",
        "ENQ_STATE": "Uttarakhand",
        "PRODUCT_NAME": "Website Designing",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "34",
        "QUERY_ID": "252153626",
        "QTYPE": "B",
        "SENDERNAME": "Babu Ali",
        "SENDEREMAIL": "murtuzaansari15356@gmail.com",
        "SUBJECT": "Requirement for Website Development Services",
        "DATE_RE": "14 Sep 2020",
        "DATE_R": "14-Sep-20",
        "DATE_TIME_RE": "14-Sep-2020 10:58:59 AM",
        "GLUSR_USR_COMPANYNAME": "Babu Store",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9398813096",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200914105859",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for 10-15 Days Satta King Game Software Development Company in India.\n\nKindly send me price and other details.<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Boropara More Bansberia, Hooghly, West Bengal,         712502",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Hooghly",
        "ENQ_STATE": "West Bengal",
        "PRODUCT_NAME": "Website Development Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "35",
        "QUERY_ID": "252152959",
        "QTYPE": "B",
        "SENDERNAME": "Parveen",
        "SENDEREMAIL": "vagad2019@gmail.com",
        "SUBJECT": "Requirement for Logo Designing Services",
        "DATE_RE": "14 Sep 2020",
        "DATE_R": "14-Sep-20",
        "DATE_TIME_RE": "14-Sep-2020 10:57:19 AM",
        "GLUSR_USR_COMPANYNAME": "Lucky Print",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8141877943",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200914105719",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I want to buy Logo and Visiting Card Designing Services.\r\n\r\nKindly send me price and other details.\r\n\r\nI am starting a new business venture.<br>Preferable Date \/ Month : 14\/09\/2020<br>Service Location : Mulund , Mumbai<br>Usage\/Application : For My Own Shop",
        "ENQ_ADDRESS": "Mumbai, Maharashtra",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Mumbai",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": "Logo Designing Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "36",
        "QUERY_ID": "1497059667",
        "QTYPE": "W",
        "SENDERNAME": "Dharmendra Singh",
        "SENDEREMAIL": "dharamsingh6568@gmail.com",
        "SUBJECT": "Requirement for Pathology Lab Software",
        "DATE_RE": "13 Sep 2020",
        "DATE_R": "13-Sep-20",
        "DATE_TIME_RE": "13-Sep-2020 09:40:41 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8840683067",
        "COUNTRY_FLAG": "",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200913214041",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I want to buy Pathology Lab Software. \n\nKindly send me price and other details.\n\n Quantity:   1   Piece\n Timeline:   After a Week \n Need Demo:   Yes \n Your Budget:   < 10k \n Why do you need this:   For Personal\/Business Use \n\n\nAdditional Updates on Buyer's Requirement :\nPreferred Location: Suppliers from Jhansi will be Preferred\n",
        "ENQ_ADDRESS": "Jhansi, Uttar Pradesh",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Jhansi",
        "ENQ_STATE": "Uttar Pradesh",
        "PRODUCT_NAME": "Pathology Lab Software",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "37",
        "QUERY_ID": "251950926",
        "QTYPE": "B",
        "SENDERNAME": "Dev Yadav",
        "SENDEREMAIL": "devyadav.tln@gmail.com",
        "SUBJECT": "Requirement for E-Commerce Website Designing Services Seo",
        "DATE_RE": "13 Sep 2020",
        "DATE_R": "13-Sep-20",
        "DATE_TIME_RE": "13-Sep-2020 07:54:24 PM",
        "GLUSR_USR_COMPANYNAME": "FT StoreS",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9893406524",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200913195424",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for E-Commerce Website Designing Services, Seo.\n\nKindly send me price and other details.<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "410, Vibrent Twin Tower, Geeta Bhawan, Indore, Madhya Pradesh,         452001",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Indore",
        "ENQ_STATE": "Madhya Pradesh",
        "PRODUCT_NAME": "E-Commerce Website Designing Services Seo",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": "+91-7770937576",
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "38",
        "QUERY_ID": "251943734",
        "QTYPE": "B",
        "SENDERNAME": "MD",
        "SENDEREMAIL": null,
        "SUBJECT": "Requirement for School Management Software",
        "DATE_RE": "13 Sep 2020",
        "DATE_R": "13-Sep-20",
        "DATE_TIME_RE": "13-Sep-2020 06:59:14 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8506906100",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200913185914",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I want to purchase School Management Software. \n\nKindly send me price and other details.<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Giridih, Jharkhand",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Giridih",
        "ENQ_STATE": "Jharkhand",
        "PRODUCT_NAME": "School Management Software",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "39",
        "QUERY_ID": "251922063",
        "QTYPE": "B",
        "SENDERNAME": "Rajesh",
        "SENDEREMAIL": "rajeshpatel.p360@gmail.com",
        "SUBJECT": "Requirement for Android Application Development Services",
        "DATE_RE": "13 Sep 2020",
        "DATE_R": "13-Sep-20",
        "DATE_TIME_RE": "13-Sep-2020 04:18:09 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9898223344",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200913161809",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for service provider for Android Application Development Services.\r\n\r\n\r\n\r\nKindly send me price and other details.<br>I am interested in : Android Application Development Services<br>Probable Unit Price : 20,000 to 50,000<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Morbi, Gujarat",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Morbi",
        "ENQ_STATE": "Gujarat",
        "PRODUCT_NAME": "Android Application Development Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "40",
        "QUERY_ID": "251906653",
        "QTYPE": "B",
        "SENDERNAME": "Mr. Shailender",
        "SENDEREMAIL": "shelendra.dixit@yahoo.com",
        "SUBJECT": "Requirement for Web Designing Services",
        "DATE_RE": "13 Sep 2020",
        "DATE_R": "13-Sep-20",
        "DATE_TIME_RE": "13-Sep-2020 02:28:19 PM",
        "GLUSR_USR_COMPANYNAME": "Vedica Trading Co.",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9411923060",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200913142819",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for service provider for Web Designing Services.\r\n\r\nKindly send me price and other details.<br>Language In Which Website Needed : English, Hindi<br>Website Type : E-Commerce Enabled<br>Why do you need this : For Business Use",
        "ENQ_ADDRESS": "Agra, Uttar Pradesh",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Agra",
        "ENQ_STATE": "Uttar Pradesh",
        "PRODUCT_NAME": "Web Designing Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "41",
        "QUERY_ID": "251906078",
        "QTYPE": "B",
        "SENDERNAME": "Bharbav",
        "SENDEREMAIL": "bhargavsavani99099@gmail.com",
        "SUBJECT": "Requirement for Android Application Development Services",
        "DATE_RE": "13 Sep 2020",
        "DATE_R": "13-Sep-20",
        "DATE_TIME_RE": "13-Sep-2020 02:24:15 PM",
        "GLUSR_USR_COMPANYNAME": "AP Fashion",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9909913067",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200913142415",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for Android Application Development.\n\nKindly send me price and other details.<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Surat, Gujarat",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Surat",
        "ENQ_STATE": "Gujarat",
        "PRODUCT_NAME": "Android Application Development Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "42",
        "QUERY_ID": "251495454",
        "QTYPE": "B",
        "SENDERNAME": "Sachin Prajapati",
        "SENDEREMAIL": "sachinprajapati9515@gmail.com",
        "SUBJECT": "Requirement for Bulk Sms Service",
        "DATE_RE": "12 Sep 2020",
        "DATE_R": "12-Sep-20",
        "DATE_TIME_RE": "12-Sep-2020 07:22:40 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9118453229",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200912192240",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for Bulk Sms Service.\n\nKindly send me price and other details.<br>Probable Requirement Type : Business Use<br>Other Products Viewed by Buyer : SMS Sending Jobs",
        "ENQ_ADDRESS": "Bahraich, Uttar Pradesh",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Bahraich",
        "ENQ_STATE": "Uttar Pradesh",
        "PRODUCT_NAME": "Bulk Sms Service",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "43",
        "QUERY_ID": "251415120",
        "QTYPE": "B",
        "SENDERNAME": "Manish",
        "SENDEREMAIL": "unnatiadvtjnp@gmail.com",
        "SUBJECT": "Requirement for Mobile Application Development Service",
        "DATE_RE": "12 Sep 2020",
        "DATE_R": "12-Sep-20",
        "DATE_TIME_RE": "12-Sep-2020 04:01:36 PM",
        "GLUSR_USR_COMPANYNAME": "Sanitising Tunnel",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-6306545807",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200912160136",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for service provider for Mobile Application Development Service.\r\nThe rest of the details I will discuss with the service providers.<br>I am interested in : Bike Application Install In Mobile<br>Service Location : Jaunpur<br>Probable Unit Price : 20,000 to 50,000<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Olandgan Jaunpur, Jaunpur, Uttar Pradesh,         222002",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Jaunpur",
        "ENQ_STATE": "Uttar Pradesh",
        "PRODUCT_NAME": "Mobile Application Development Service",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "44",
        "QUERY_ID": "251383314",
        "QTYPE": "B",
        "SENDERNAME": "Sanchi",
        "SENDEREMAIL": "sachinprachi9166@gmail.com",
        "SUBJECT": "Requirement for Ecommerce Website Design Service",
        "DATE_RE": "12 Sep 2020",
        "DATE_R": "12-Sep-20",
        "DATE_TIME_RE": "12-Sep-2020 02:41:43 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9024317386",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200912144143",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for service provider for Ecommerce Website Design Service.\r\n\r\nKindly send me price and other details.<br>Website Already Exists : No<br>Template Type : Customized<br>Job Completion Timeframe : 1month<br>Probable Unit Price : Rs. 10,000 - 30,000",
        "ENQ_ADDRESS": "Ajmer, Rajasthan",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Ajmer",
        "ENQ_STATE": "Rajasthan",
        "PRODUCT_NAME": "Ecommerce Website Design Service",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "45",
        "QUERY_ID": "251357622",
        "QTYPE": "B",
        "SENDERNAME": "Rakesh Gupta",
        "SENDEREMAIL": "rkgpolyplast@gmail.com",
        "SUBJECT": "Requirement for Matrimonial Website Development",
        "DATE_RE": "12 Sep 2020",
        "DATE_R": "12-Sep-20",
        "DATE_TIME_RE": "12-Sep-2020 01:26:42 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9810023250",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200912132642",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "We want matrimonial website for charitable trust at delhi.<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "New Delhi, Delhi",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "New Delhi",
        "ENQ_STATE": "Delhi",
        "PRODUCT_NAME": "Matrimonial Website Development",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "46",
        "QUERY_ID": "251341307",
        "QTYPE": "B",
        "SENDERNAME": "Subramanya Devadiga",
        "SENDEREMAIL": "subbu3374@gmail.com",
        "SUBJECT": "Requirement for Online Android Application Development Services",
        "DATE_RE": "12 Sep 2020",
        "DATE_R": "12-Sep-20",
        "DATE_TIME_RE": "12-Sep-2020 12:43:07 PM",
        "GLUSR_USR_COMPANYNAME": "Indicraft",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8660704066",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200912124307",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am interested in Online Android Application Development Services<br>Probable Unit Price : 20,000 to 50,000<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Uttara Kannada, Bhatkal, Karnataka,         581421",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Bhatkal",
        "ENQ_STATE": "Karnataka",
        "PRODUCT_NAME": "Online Android Application Development Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "47",
        "QUERY_ID": "251099920",
        "QTYPE": "B",
        "SENDERNAME": "Amaan Ansari",
        "SENDEREMAIL": "amaanansari0780@gmail.com",
        "SUBJECT": "Requirement for Software Development Services",
        "DATE_RE": "11 Sep 2020",
        "DATE_R": "11-Sep-20",
        "DATE_TIME_RE": "11-Sep-2020 08:08:25 PM",
        "GLUSR_USR_COMPANYNAME": "Ansari Telecom Center",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9336495905",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200911200825",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for Software Development Services.\n\nKindly send me price and other details.<br>Probable Unit Price : 20,000 to 50,000<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Barabanki, Uttar Pradesh",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Barabanki",
        "ENQ_STATE": "Uttar Pradesh",
        "PRODUCT_NAME": "Software Development Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "48",
        "QUERY_ID": "250992369",
        "QTYPE": "B",
        "SENDERNAME": "Akash",
        "SENDEREMAIL": "akashjakhru7@gmail.com",
        "SUBJECT": "Requirement for Hospital Management Advance Software",
        "DATE_RE": "11 Sep 2020",
        "DATE_R": "11-Sep-20",
        "DATE_TIME_RE": "11-Sep-2020 01:38:40 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8141977959",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200911133840",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I want to buy Hospital Management Advance Software. \n\nKindly send me price and other details.<br>Quantity : 1 Piece<br>Need Demo : Yes<br>Probable Requirement Type : Business Use<br>Probable Order Value : Rs. 10,000 - 40,000",
        "ENQ_ADDRESS": "Allahabad, Uttar Pradesh",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Allahabad",
        "ENQ_STATE": "Uttar Pradesh",
        "PRODUCT_NAME": "Hospital Management Advance Software",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "49",
        "QUERY_ID": "250968970",
        "QTYPE": "B",
        "SENDERNAME": "Anshul",
        "SENDEREMAIL": "anshulgupta0307@gmail.com",
        "SUBJECT": "Requirement for Android Application Development Services",
        "DATE_RE": "11 Sep 2020",
        "DATE_R": "11-Sep-20",
        "DATE_TIME_RE": "11-Sep-2020 12:30:56 PM",
        "GLUSR_USR_COMPANYNAME": "Gupta Store",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9828683938",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200911123056",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for service provider for Android Application Development Services.\r\n\r\nKindly send me price and other details.<br>I am interested in : IOS Application Development, Android Application Development Services<br>Project Duration : 4 Month<br>Start Date \/ Month : February  2021<br>Service Location : Jaipur , Rajasthan<br>Probable Unit Price : 20,000 to 50,000<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Shop No.37, Raisar Plaza, Man Market Kurgaon Karauli, Karauli, Rajasthan,         302255",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Karauli",
        "ENQ_STATE": "Rajasthan",
        "PRODUCT_NAME": "Android Application Development Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "50",
        "QUERY_ID": "250968440",
        "QTYPE": "B",
        "SENDERNAME": "Rajan",
        "SENDEREMAIL": "vishwakarmaramchandra1@gmail.com",
        "SUBJECT": "Requirement for Website Development Services",
        "DATE_RE": "11 Sep 2020",
        "DATE_R": "11-Sep-20",
        "DATE_TIME_RE": "11-Sep-2020 12:29:34 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9820588348",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200911122934",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am interested in 7- 10 Days Website Development Services<br>Service Location : PAN India<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Mumbai, Maharashtra",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Mumbai",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": "Website Development Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "51",
        "QUERY_ID": "250901367",
        "QTYPE": "B",
        "SENDERNAME": "Toufik Bagwan",
        "SENDEREMAIL": "toufikfruits@gmail.com",
        "SUBJECT": "Requirement for Mobile Application Development",
        "DATE_RE": "11 Sep 2020",
        "DATE_R": "11-Sep-20",
        "DATE_TIME_RE": "11-Sep-2020 09:21:48 AM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9970786797",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200911092148",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "N",
        "ENQ_ADDRESS": "Ahmednagar, Maharashtra",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Ahmednagar",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": "Mobile Application Development",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": "+91-9270786797",
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "52",
        "QUERY_ID": "250739547",
        "QTYPE": "B",
        "SENDERNAME": "Madhan",
        "SENDEREMAIL": "racha.madhi@gmail.com",
        "SUBJECT": "Requirement for Dynamic Website Designing Service",
        "DATE_RE": "10 Sep 2020",
        "DATE_R": "10-Sep-20",
        "DATE_TIME_RE": "10-Sep-2020 07:32:54 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8008787123",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200910193254",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I want to buy Dynamic Website Designing Service.\n\nMain requirements \n 1 customers can create accounts and log in\n 2 able to fill a form (similar to survey )\n 3 should have wallet functions for every account( no payment integration needed ) \n 4 for every filled survey there should be ref no. And \n 5.Sms integration for message to every form filled and transactions\n\nKindly send me price and other details.<br>Language In Which Website Needed : English<br>Services Required : Development only<br>Website Type : service based website<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Karimnagar, Telangana",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Karimnagar",
        "ENQ_STATE": "Telangana",
        "PRODUCT_NAME": "Dynamic Website Designing Service",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "53",
        "QUERY_ID": "250702190",
        "QTYPE": "B",
        "SENDERNAME": "Manikanta",
        "SENDEREMAIL": "amoghyelahanka@gmail.com",
        "SUBJECT": "Requirement for Hospital Management Systems",
        "DATE_RE": "10 Sep 2020",
        "DATE_R": "10-Sep-20",
        "DATE_TIME_RE": "10-Sep-2020 04:44:49 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9686160565",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200910164449",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am interested in buying Hospital Management Systems. \n\nKindly send me price and other details.<br>Quantity : 100 Piece<br>Probable Requirement Type : Business Use<br>Probable Order Value : 20 to 50 Lakh",
        "ENQ_ADDRESS": "Bengaluru, Karnataka",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Bengaluru",
        "ENQ_STATE": "Karnataka",
        "PRODUCT_NAME": "Hospital Management Systems",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "54",
        "QUERY_ID": "250692856",
        "QTYPE": "B",
        "SENDERNAME": "Sheetal Patil",
        "SENDEREMAIL": "sheetalkunwar4816@gmail.com",
        "SUBJECT": "Requirement for Hospital Management System",
        "DATE_RE": "10 Sep 2020",
        "DATE_R": "10-Sep-20",
        "DATE_TIME_RE": "10-Sep-2020 04:13:05 PM",
        "GLUSR_USR_COMPANYNAME": "SS Health Solutions",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9834510765",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200910161305",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "My Requirement is for Hospital Management System. \n\nKindly send me price and other details.<br>Probable Unit Price : 20,000 to 50,000",
        "ENQ_ADDRESS": "Ganraj Heights, 401 Manaji Nagar, Marhe, Pune, Maharashtra,         411041",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Pune",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": "Hospital Management System",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": "+91-9372353691",
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "55",
        "QUERY_ID": "250628962",
        "QTYPE": "B",
        "SENDERNAME": "Krishna",
        "SENDEREMAIL": "krishnak64639@gmail.com",
        "SUBJECT": "Requirement for Ecommerce Development Solution Service",
        "DATE_RE": "10 Sep 2020",
        "DATE_R": "10-Sep-20",
        "DATE_TIME_RE": "10-Sep-2020 12:36:43 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9144987394",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200910123643",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for Ecommerce Development Solution Service.\n\nKindly send me price and other details.<br>Service Location : Pune<br>Usage\/Application : Courier",
        "ENQ_ADDRESS": "Pune, Maharashtra",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Pune",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": "Ecommerce Development Solution Service",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "56",
        "QUERY_ID": "250571516",
        "QTYPE": "B",
        "SENDERNAME": "Sunil",
        "SENDEREMAIL": "sunil.kumar.myid@gmail.com",
        "SUBJECT": "Requirement for School Management Software",
        "DATE_RE": "10 Sep 2020",
        "DATE_R": "10-Sep-20",
        "DATE_TIME_RE": "10-Sep-2020 09:54:03 AM",
        "GLUSR_USR_COMPANYNAME": "Army Public School, Devlali",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9226883479",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200910095403",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am interested in buying School Management Software. \n\nKindly send me price and other details.<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "Nashik, Maharashtra",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Nashik",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": "School Management Software",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "57",
        "QUERY_ID": "250557274",
        "QTYPE": "B",
        "SENDERNAME": "Kuntal",
        "SENDEREMAIL": null,
        "SUBJECT": "Requirement for Covid-19 Hospital Patient Management System",
        "DATE_RE": "10 Sep 2020",
        "DATE_R": "10-Sep-20",
        "DATE_TIME_RE": "10-Sep-2020 08:20:38 AM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-8370862235",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200910082038",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "My Requirement is for Covid-19 Hospital Patient Management System. \n\nKindly send me price and other details.<br>Probable Unit Price : 20,000 to 50,000",
        "ENQ_ADDRESS": "Diamond Harbour, West Bengal",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Diamond Harbour",
        "ENQ_STATE": "West Bengal",
        "PRODUCT_NAME": "Covid-19 Hospital Patient Management System",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "58",
        "QUERY_ID": "250351095",
        "QTYPE": "B",
        "SENDERNAME": "Ranjan",
        "SENDEREMAIL": null,
        "SUBJECT": "Requirement for Mobile App Development Service",
        "DATE_RE": "09 Sep 2020",
        "DATE_R": "09-Sep-20",
        "DATE_TIME_RE": "09-Sep-2020 03:47:17 PM",
        "GLUSR_USR_COMPANYNAME": null,
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-6392653921",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200909154717",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for Mobile App Development Service.\n\nKindly send me price and other details.<br>Probable Requirement Type : Business Use<br>Project Duration : Business Use",
        "ENQ_ADDRESS": "Allahabad, Uttar Pradesh",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Allahabad",
        "ENQ_STATE": "Uttar Pradesh",
        "PRODUCT_NAME": "Mobile App Development Service",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "59",
        "QUERY_ID": "250328867",
        "QTYPE": "B",
        "SENDERNAME": "Pavend",
        "SENDEREMAIL": null,
        "SUBJECT": "Requirement for Mobile Application Development",
        "DATE_RE": "09 Sep 2020",
        "DATE_R": "09-Sep-20",
        "DATE_TIME_RE": "09-Sep-2020 02:25:56 PM",
        "GLUSR_USR_COMPANYNAME": "Kapil Grah Udhyog",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9309176271",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200909142556",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for service provider for Mobile Application Development.<br>Probable Unit Price : 20,000 to 50,000<br>Why do you need this : For Business Use",
        "ENQ_ADDRESS": "Nagpur, Maharashtra",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Nagpur",
        "ENQ_STATE": "Maharashtra",
        "PRODUCT_NAME": "Mobile Application Development",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    },
    {
        "RN": "60",
        "QUERY_ID": "250246879",
        "QTYPE": "B",
        "SENDERNAME": "Rahul",
        "SENDEREMAIL": "gurjardairy930@gmail.com",
        "SUBJECT": "Requirement for Logo Designer Services",
        "DATE_RE": "09 Sep 2020",
        "DATE_R": "09-Sep-20",
        "DATE_TIME_RE": "09-Sep-2020 10:01:35 AM",
        "GLUSR_USR_COMPANYNAME": "Siddh Baba Gurjar Dairy",
        "READ_STATUS": null,
        "SENDER_GLUSR_USR_ID": null,
        "MOB": "+91-9301220564",
        "COUNTRY_FLAG": "https:\/\/1.imimg.com\/country-flags\/small\/in_flag_s.png",
        "QUERY_MODID": "DIRECT",
        "LOG_TIME": "20200909100135",
        "QUERY_MODREFID": null,
        "DIR_QUERY_MODREF_TYPE": null,
        "ORG_SENDER_GLUSR_ID": null,
        "ENQ_MESSAGE": "I am looking for Logo Designer Services.\n\nKindly send me price and other details.<br>I am interested in : 3D Logo Design<br>Probable Requirement Type : Business Use",
        "ENQ_ADDRESS": "R B. Colony, Tansen Road, Gwalior, Madhya Pradesh,         474002",
        "ENQ_CALL_DURATION": null,
        "ENQ_RECEIVER_MOB": null,
        "ENQ_CITY": "Gwalior",
        "ENQ_STATE": "Madhya Pradesh",
        "PRODUCT_NAME": "Logo Designer Services",
        "COUNTRY_ISO": "IN",
        "EMAIL_ALT": null,
        "MOBILE_ALT": null,
        "PHONE": null,
        "PHONE_ALT": null,
        "IM_MEMBER_SINCE": null,
        "TOTAL_COUNT": "60"
    }
]